const userData = {
  githubUsername: "rajshah4",
  name: "Rajiv Shah",
  designation: "Data Scientist",
  avatarUrl: "/avatar.png",
  email: "rshah@pobox.com",
  phone: "1-309-310-3622",
  address: "Illinois, USA",
 upcoming: [
      {
      title: "MLOps World 2025: From Vectors to Agents: Managing RAG in an Agentic World",
      date: "October 2025",
      link: "https://mlopsworld.com/",
      imgUrl: "/MLOps_2025.png",
    },
    {
      title: "ODSC: Evaluation for Generative AI",
      date: "October 2025",
      link: "https://odsc.ai/west",
      imgUrl: "/ODSC_2025.png",
    },
    {
      title: "WANDB: Fully Connected London",
      date: "Nov 2025",
      link: "https://wandb.ai/site/resources/events/fully-connected/london/",
      imgUrl: "/WANDB_2025.webp",
    },
        {
      title: "Midwest AI Summit: 95% Failures. 5% Winners. How to Beat the Odds in AI",
      date: "November 2025",
      link: "https://midwestaisummit.com/",
      imgUrl: "/MID_2025.png",
    }
  ],
  highlight: [
    {
      title: "We've all done RAG, now what? (Practical AI Podcast)",
      link: "https://practicalai.fm/330",
      imgUrl: "/practical_2025.png",
    },
    {
      title: "Forget RAG Pipelines—Build Production Ready Agents in 15 Mins",
      link: "https://www.youtube.com/watch?v=lArgRvBV3tQ",
      imgUrl: "/AIEngineer_2025.jpg",
    },
    {
      title: "Evaluation for Large Language Models and Generative AI -- Updated 2025",
      link: "https://youtu.be/hWlv4e6SQbU",
      imgUrl: "/Evaluation_2025.png",
    },
    {
      title: "Evaluation for Large Language Models and Generative AI - A Deep Dive",
      link: "https://youtu.be/iQl03pQlYWY?si=kvQxuiYzUVDyIuCm",
      imgUrl: "/Evaluation2023.png",
    },
  ],
  about: {
    title1: "I help enterprises with the latest AI.",
    title2: "I keep a side mission of educating folks about AI - follow @rajistics.",
    currentPosition: "Chief Evangelist at Contextual AI",
    currentPositiontUrl: "https://www.contextual.ai",
  },
  bio: {
    description: [
      `Rajiv Shah is the Chief Evangelist at Contextual AI with a passion and expertise in Practical AI. He focuses on enabling enterprise teams to succeed with AI. Rajiv has worked on GTM teams at leading AI companies, including Hugging Face in open-source AI, Snorkel in data-centric AI, Snowflake in cloud computing, and DataRobot in AutoML. He started his career in data science at State Farm and Caterpillar.`,
      `Rajiv is a widely recognized speaker on AI, published over 20 research papers, been cited over 1000 times, and received over 20 patents. His recent work in AI covers topics such as sports analytics, deep learning, and interpretability.`,  
      `Rajiv holds a PhD in Communications and a Juris Doctor from the University of Illinois at Urbana Champaign. While earning his degrees, he received a fellowship in Digital Government from the John F. Kennedy School of Government at Harvard University. He is well known on social media with his short videos, @rajistics, that have received over ten million views.`
    ],
  },
  experience: [
    {
      title: "Chief Evangelist",
      company: "Contextual AI",
      year: "2025",
      companyLink: "https://contextual.ai/",
      desc: "Sharing the Possibilities of Agentic RAG",
    },
    {
      title: "Machine Learning Engineer",
      company: "Contextual AI",
      year: "2024",
      companyLink: "https://contextual.ai/",
      desc: "Focused on GTM for AI/ML for Production-Ready RAG Enterprise AI.",
    },
    {
      title: "AI/ML Strategy",
      company: "Snowflake",
      year: "2024",
      companyLink: "https://www.snowflake.com/en/",
      desc: "Focused on GTM for AI/ML for the largest Enterprise Accounts at Snowflake.",
    },
    {
      title: "Machine Learning Engineer",
      company: "Hugging Face",
      year: "2022",
      companyLink: "https://huggingface.co",
      desc: "Founding member of Enterprise GTM team focusing on Pre-Sales. 5X Customer Growth",
    },
    {
      title: "Machine Learning Solutions Engineer",
      company: "Snorkel AI",
      year: "2021",
      companyLink: "https://snorkel.ai",
      desc: "Founding member of Enterprise GTM team focusing on Pre-Sales. 3X Customer Growth",
    },
    {
      title: "Principal Data Scientist and Director, GTM Technical Enablement",
      company: "DataRobot",
      year: "2020",
      companyLink: "https://datarobot.com",
      desc: "Led Technical Enablement for hundreds of data scientists",
    },
    {
      title: "Customer Facing Data Scientist",
      company: "DataRobot",
      year: "2017",
      companyLink: "https://datarobot.com",
      desc: "Pre/Post Sales across the US Central Region",
    },
    {
      title: "Senior Data Scientist",
      company: "Caterpillar",
      year: "2016",
      companyLink: "https://caterpillar.com",
      desc: "Multiple projects, but based in the Global Supply Network Divsion",
    },
    {
      title: "Data Scientist",
      company: "State Farm",
      year: "2014",
      companyLink: "https://statefarm.com",
      desc: "Founding member of data science team",
    },
    {
      title: "Adjunct Assistant Professor",
      company: "University of Illinois at Chicago",
      year: "2005",
      companyLink: "https://comm.uic.edu/profiles/rajiv-shah/",
      desc: "Long affiliation and conducted research in Chicago",
    },
  ],
  resumeUrl: "/CVShah2023.pdf",
  SSRNUrl: "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=261155",
  GoogleSUrl: "https://scholar.google.com/citations?user=J6N60VcAAAAJ&hl=en",
  MediumUrl: "https://medium.com/@rajistics",
  BlogUrl: "https://projects.rajivshah.com/blog/",
  socialLinks: {
    instagram: "https://instagram.com/rajistics",
    twitter: "https://twitter.com/rajistics",
    linkedin: "https://linkedin.com/in/rajistics",
    github: "https://github.com/rajshah4",
    facebook: "https://facebook.com/",
    tiktok: "https://www.tiktok.com/@rajistics",
    youtube: "https://www.youtube.com/c/Rajistics",
    reddit: "https://www.reddit.com/r/rajistics/",
  },
  blogpost: [
    {
      title: "Evaluation Mindset: Taming the Gen AI Dragon",
      date:  "Apr 2025",
      source: "Medium",
      link: "https://medium.com/@rajistics/evaluation-mindset-taming-the-gen-ai-dragon-aa16bf7c8694",
    },
    {
      title: "Understanding Sparse Matrices through Interactive Visualizations",
      date:  "Mar 2025",
      source: "RajivShah",
      link: "https://projects.rajivshah.com/blog/sparsedataframe.html",
    },
    {
      title: "Feature Selection Methods and Feature Selection Curves",
      date:  "Oct 2024",
      source: "RajivShah",
      link: "https://projects.rajivshah.com/blog/Feature_Selection.html",
    },
    {
      title: "The honeymoon phase of generative AI is over",
      date:  "Jun 2024",
      source: "LinkedIn",
      link: "https://www.linkedin.com/feed/update/urn:li:activity:7207753303546372098",
    },
    {
      title: "GPT-4 Loses: Data Labeling with LLMs",
      date:  "Oct 2023",
      source: "LinkedIn",
      link: "https://www.linkedin.com/feed/update/urn:li:activity:7120746362236792832",
    },
    {
      title: "FinBERT beats GPT-4",
      date:  "Sep 2023",
      source: "LinkedIn",
      link: "https://www.linkedin.com/feed/update/urn:li:activity:7108090020875444225",
    },
    {
      title: "Lessons earned from Bloomberg GPT",
      date:  "Aug 2023",
      source: "LinkedIn",
      link: "https://www.linkedin.com/feed/update/urn:li:activity:7089609531961348096",
    },
    {
      title: "FinBERT beats GPT-3",
      date:  "Feb 2023",
      source: "LinkedIn",
      link: "https://www.linkedin.com/feed/update/urn:li:activity:7024363501318000640",
    },
    {
      title: "Reasoning in Large Language Models",
      date:  "Feb 2023",
      source: "Medium",
      link: "https://medium.com/@rajistics/reasoning-in-large-language-models-2ff33c318a94",
    },
    {
      title: "Data Science News Sources",
      date: "Dec 2022",
      source: "Medium",
      link: "https://medium.com/@rajistics/data-science-news-sources-71ad418242b4", 
    },
    {
      title: "Accelerating Document AI",
      date: "Nov 2022",
      source: "Hugging Face",
      link: "https://huggingface.co/blog/document-ai", 
    },
    {
      title: "Text style transfer in a spreadsheet using Hugging Face Inference Endpoints",
      date: "Nov 2022",
      source: "Medium",
      link: "https://medium.com/@rajistics/text-style-transfer-in-a-spreadsheet-using-hugging-face-inference-endpoints-cc55e4bd58b",
    },
    {
      title: "Few shot text classification with SetFit",
      date: "Oct 2022",
      source: "Medium",
      link: "https://medium.com/@rajistics/few-shot-text-classification-with-setfit-63ff7a02da5e",
    },
    {
      title: "Getting predictions intervals with conformal inference",
      date: "Sep 2022",
      source: "Medium",
      link: "https://medium.com/@rajistics/getting-predictions-intervals-with-conformal-inference-caff5be40eff",
    },
    {
      title: "Explaining predictions from 🤗 transformer models",
      date: "Aug 2022",
      source: "Medium",
      link: "https://medium.com/@rajistics/explaining-predictions-from-transformer-models-55ab9c6cab24",
    },
    {
      title: "Dynamic Adversarial Data Collection",
      date: "Aug 2022",
      source: "Medium",
      link: "https://medium.com/@rajistics/dynamic-adversarial-data-collection-712df9bac786",
    },
    {
      title: "Fine-Tuning for Image Classification using Transformers",
      date: "Aug 2022",
      source: "Medium",
      link: "https://medium.com/@rajistics/fine-tuning-for-image-classification-using-transformers-7ca01aeb7766",
    },
    {
      title: "The Art of Sprezzatura for Machine Learning: Building Interpretable Models",
      date: "Dec 2021",
      source: "Medium",
      link: "https://towardsdatascience.com/the-art-of-sprezzatura-for-machine-learning-e2494c0db727",
    },
    {
      title: "AI Use Cases for Cyber and Malware Analysts",
      date: "July 2021",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/ai-use-cases-for-cyber-and-malware-analysts/",
    },
    {
      title: "How MLOps Helps You Dodge The Wrecking Ball of Underspecification",
      date: "June 2021",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/how-mlops-helps-you-dodge-the-wrecking-ball-of-underspecification/",
    },
    {
      title: "Running Code and Failing Models",
      date: "Feb 2021",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/running-code-and-failing-models/",
    },
    {
      title: "Using Feature Importance Rank Ensembling (FIRE) for Advanced Feature Selection",
      date: "Jan 2021",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/using-feature-importance-rank-ensembling-fire-for-advanced-feature-selection/",
    },
    {
      title: "Predicting Music Genre Based on the Album Cover",
      date: "Aug 2020",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/predicting-music-genre-based-on-the-album-cover/",
    },
    {
      title: "Improving Model Management in Uncertain Times",
      date: "Jun 2020",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/improving-model-management-in-uncertain-times/",
    },
    {
      title: "Using Small Datasets to Build Models",
      date: "Apr 2020",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/using-small-datasets-to-build-models/",
    },
    {
      title: "AI in Turbulent Times: Navigating Changing Conditions Webinar",
      date: "Mar 2020",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/ai-in-turbulent-times-navigating-changing-conditions-webinar/",
    },
    {
      title: "Stand Up for Best Practices: Misuse of Deep Learning in Nature’s Earthquake Aftershock Paper",
      date: "Jun 2019",
      source: "Medium",
      link: "https://towardsdatascience.com/stand-up-for-best-practices-8a8433d3e0e8",
    },
    {
      title: "Using Machine Learning to Peek Inside the Minds of NFL Coaches",
      date: "Jan 2019",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/using-machine-learning-to-peek-inside-the-minds-of-nfl-coaches/",
    },
    {
      title: "Taking Fantasy Football Analytics to the Next Level with Automated Machine Learning",
      date: "Sep 2018",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/taking-fantasy-football-analytics-to-the-next-level-with-automated-machine-learning/",
    },
    {
      title: "Optimization Strategies",
      date: "July 2018",
      source: "Medium",
      link: "https://medium.com/@rajistics/optimization-strategies-2fd23afe29f8",
    },
    {
      title: "Measure Once, Cut Twice: Moving Towards Iteration in Data Science",
      date: "Feb 2018",
      source: "DataRobot",
      link: "https://www.datarobot.com/blog/measure-once-cut-twice-moving-towards-iteration-in-data-science/s",
    },
    {
      title: "Using Unlabeled Data to Label Data",
      date: "Jan 2018",
      source: "Medium",
      link: "https://medium.com/@rajistics/using-unlabeled-data-to-label-data-8d8ee8e707ab",
    },
    {
      title: "Using Google’s Quickdraw to create an MNIST style dataset!",
      date: "July 2017",
      source: "Medium",
      link: "https://medium.com/@rajistics/using-googles-quickdraw-to-create-an-mnist-style-dataset-709c0f99bc65",
    },
    {
      title: "Using xgbfi for revealing feature interactions",
      date: "Aug 2016",
      source: "Medium",
      link: "https://medium.com/@rajistics/using-xgbfi-for-revealing-feature-interactions-834cb3d33b02",
    },
    {
      title: "Outlier App",
      date: "Jun 2016",
      source: "Medium",
      link: "https://medium.com/@rajistics/outlier-app-ec01941f36a4",
    },
    {
      title: "SportVu Analysis",
      date: "Apr 2016",
      source: "Medium",
      link: "https://medium.com/@rajistics/sportvu-analysis-38cdf3e260e1",
    },
  ],
  video: [
    {
      title: "Evaluation for Generative AI - A simply explained starting point",
      date:  "May 2025",
      source: "Youtube",
      link: "https://youtu.be/hWlv4e6SQbU",
    },
    {
      title: "Using Reasoning LLMs (Claude with Python or Agno)",
      date:  "Apr 2025",
      source: "Youtube",
      link: "https://youtu.be/3mV56gcGt84",
    },
    {
      title: "Get Started with Deepseek's GRPO using QWEN and Hugging Face",
      date:  "Feb 2025",
      source: "Youtube",
      link: "https://youtu.be/AjcvMN1kK-g?si=iNHaoedLUiD_ThDL",
    },
    {
      title: "Unit Testing for Natural Language (LLMs) + LMUnit model",
      date:  "Feb 2025",
      source: "Youtube",
      link: "https://youtu.be/5KRUvmO7LyQ?si=ONmhZsLdByfksgkg",
    },
    {
      title: "Training Kolmogorov-Arnold Networks (KAN) using Pytorch and Nixtla on M3/M4 Time Series Datasets",
      date:  "Nov 2024",
      source: "Youtube",
      link: "https://youtu.be/LaAlEqMtzLU",
    },
    {
      title: "Feature Selection Methods for Machine Learning, plus Feature Selection Curves",
      date:  "Oct 2024",
      source: "Youtube",
      link: "https://youtu.be/jm7TYGv32zs",
    },
    {
      title: "Start using Llama 3.2 Vision Models with Hugging Face Transformers (on Snowflake)",
      date:  "Oct 2024",
      source: "Youtube",
      link: "https://youtu.be/uNbG7P7EEFY",
    },
    {
      title: "Practical Lessons in Building Generative AI: RAG and Text to SQL",
      date:  "Sep 2024",
      source: "Youtube",
      link: "https://youtu.be/OyY4uxUShys",
    },
    {
      title: "Spark of AI: How Transfer Learning Unlocked AI's Potential",
      date:  "Sep 2024",
      source: "Youtube",
      link: "https://youtu.be/6NuGEukBfcA?si=--wU8BUi75rxPOoY",
    },
    {
      title: "Rules: A Simple & Effective Machine Learning Approach",
      date:  "Aug 2024",
      source: "Youtube",
      link: "https://youtu.be/lx4SJOVtxI8?si=J-lxG8ECG9tbvPi0",
    },
    {
      title: "Intro to Generative AI and Trends (March 2024)",
      date:  "Jun 2024",
      source: "Youtube",
      link: "https://youtu.be/HWL66sD1uo0?si=DLSTFAOVE_fRWlVS",
    },
    {
      title: "Model Interpretability and Explainability for Machine Learning Models",
      date:  "Jun 2024",
      source: "Youtube",
      link: "https://youtu.be/ZRckw_fE56Q?si=s8cZdXOVI-KZupFU",
    },
    {
      title: "Large Language Models (LLMs) Can Explain Their Predictions",
      date:  "Jan 2024",
      source: "Youtube",
      link: "https://youtu.be/9RFz3cQ9NqE?si=yGIJUFkMSCalbLob",
    },
    {
      title: "Evaluation for Large Language Models and Generative AI - A Deep Dive",
      date:  "Nov 2023",
      source: "Youtube",
      link: "https://youtu.be/iQl03pQlYWY?si=kvQxuiYzUVDyIuCm",
    },
    {
      title: "NanoGPT using Simpsons Data: Get Started with Large Language Models",
      date:  "Sep 2023",
      source: "Youtube",
      link: "https://youtu.be/Ty2_bR1mrBQ",
    },
    {
      title: "16 Challenges for LLMs - Paper Highlights",
      date:  "Aug 2023",
      source: "Youtube",
      link: "https://youtu.be/B5MhLSapnms",
    },
    {
      title: "Llama 2 Paper Explained",
      date:  "July 2023",
      source: "Youtube",
      link: "https://youtu.be/idmhH9_H1hY",
    },
    {
      title: "GPT or BERT? Reviewing the tradeoffs of using Large Language Models versus smaller models",
      date:  "Jun 2023",
      source: "Youtube",
      link: "https://youtu.be/1Kaj5H_YARg",
    },
    {
      title: "Building Better Large Language Models - Key Concepts for Prompting and Fine Tuning",
      date:  "Apr 2023",
      source: "Youtube",
      link: "https://youtu.be/NjtKcnLzo3g",
    },
    {
      title: "Efficient Large Language Model training with LoRA and Hugging Face PEFT",
      date:  "Mar 2023",
      source: "Youtube",
      link: "https://youtu.be/YKCtbIJC3kQ",
    },
    {
      title: "Text style transfer in a spreadsheet using Hugging Face Inference Endpoints",
      date: "Nov 2022",
      source: "Youtube",
      link: "https://youtu.be/jA6VDKO7XfA", 
    },
    {
      title: "SetFit: Few Shot Learning for Text Classification",
      date: "Oct 2022",
      source: "Youtube",
      link: "https://youtu.be/ZUK4zR0IeLU", 
    },
    {
      title: "Prediction Intervals with Conformal Inference: An Intuitive Explanation",
      date: "Sep 2022",
      source: "Youtube",
      link: "https://youtu.be/ZUK4zR0IeLU", 
    },
    {
      title: "LayoutLMv3 Training with CORD (receipts dataset)",
      date: "Sep 2022",
      source: "Youtube",
      link: "https://youtu.be/bsT_1uDRQVo", 
    },
    {
      title: "Fine Tuning an Image Classifier on Indian Food Images",
      date: "Aug 2022",
      source: "Youtube",
      link: "https://youtu.be/j6WbCS0GLuY", 
    },
    {
      title: "Explanation Approaches for Transformers",
      date: "Aug 2022",
      source: "Youtube",
      link: "https://youtu.be/ahgB8c_TgA8", 
    }
  ],
  talks: [
    {
      title: "Evaluation for Generative AI",
      date: "May 2025",
      source: "ODSC East",
      link: "https://youtu.be/hWlv4e6SQbU",
    },
    {
      title: "Practical Generative AI for Executives",
      date: "Oct 2024",
      source: "Insurance Collection Executives",
      link: "https://theicesite.com/content.aspx?page_id=22&club_id=180006&module_id=671206",
    },
    {
      title: "Spark of the AI Revolution: How Transfer Learning Unlocked AI's Potential",
      date: "Sep 2024",
      source: "University of Cincinnati",
      link: "https://www.linkedin.com/posts/rajistics_how-does-ai-learn-lets-dig-into-transfer-activity-7234220838982410240-b56W/",
    },
    {
      title: "AV Luminary Awards for the Top 10 AI Community Contributors",
      date: "Aug 2024",
      source: "Analytics Vidhya",
      link: "https://www.linkedin.com/feed/update/urn:li:activity:7226906469428867072/",
    },
    {
      title: "Want ROI from genAI? Rethink what both terms mean",
      date: "Jul 2024",
      source: "ComputerWorld",
      link: "https://www.computerworld.com/article/2517737/want-roi-from-genai-rethink-what-both-terms-mean.html",
    },
    {
      title: "E13: Navigating the Evolving World of Open Source AI with Rajiv Shah",
      date: "May 2024",
      source: "Practically Intelligent Podcast",
      link: "https://youtu.be/lhAyZoYMdxM?si=kdyFkrOAWGQh-o-8",
    },
    {
      title: "GenAI in the Enterprise w/ Raj Shah, ML Engineer at Snowflake",
      date: "May 2024",
      source: "Zach Gardner / Keyhole Software",
      link: "https://youtu.be/cEN_dA4mEA8?si=XbfVDDw2avIjtkpc",
    },
    {
      title: "Practical Perspective on Generative AI",
      date: "May 2024",
      source: "Gateway to Innovation Conference",
      link: "https://www.g2iconference.com/agenda",
    },
    {
      title: "Generative AI: A Survey of Current Practices, Challenges, and Best Practices",
      date: "March 2024",
      source: "R Govsys",
      link: "https://youtu.be/UHDIgsWmqtE?si=j4LOiGtvyMjYCFdg",
    },
    {
      title: "Journey from Military Curiosity to AI Leadership",
      date: "Feb 2024",
      source: "Analytics Vidhya",
      link: "https://youtu.be/d6CZoXh670o?si=4_EKe1sesr7qjfkh",
    },
    {
      title: "Evaluation Techniques for Large Language Models – Interview with Rajiv Shah, Hugging Face",
      date:  "Feb 2024",
      source: "Hyperight / Data Innovation Summit 2024",
      link: "https://hyperight.com/evaluation-techniques-for-large-language-models-interview-with-rajiv-shah-hugging-face/",
    },
    {
      title: "Exploring Language Model Evaluation with Rajiv Shah",
      date:  "Jan 2024",
      source: "LLM Daily",
      link: "https://www.youtube.com/watch?v=io8FlI-_gOo&ab_channel=LLMDaily",
    },
    {
      title: "Choosing the Right LLM for Your Organization’s Needs",
      date: "December 2023",
      source: "DataRobot Webinar",
      link: "https://www.datarobot.com/webinars/choosing-the-best-llm-for-your-organization/", 
    },
       {
      title: "Evaluation Techniques for Large Language Models",
      date: "Novemeber 2023",
      source: "MLOPS World",
      link: "https://youtu.be/vqO7ks7DFZw?si=x69yYhZjRnOp4xP8", 
    },
    {
      title: "Constructing an Evaluation Approach for Generative AI Models",
      date: "December 2023",
      source: "Arize AI Holiday Special",
      link: "https://youtu.be/PtXOQDHPddE?si=PQ4N1B2mX2d_9PwC&t=147", 
    },
    {
      title: "The Future of Generative AI: Vision and Challenges",
      date: "September 2023",
      source: "Generative AI World Summit",
      link: "https://www.youtube.com/live/2mvvx9puQ_E?si=REQos2ZRqOY9eCNJ", 
    },
    {
      title: "How to Leverage Open-Source LLMs in Your Project",
      date:"August 2023",
      source: "Turing Post",
      link: "https://www.turingpost.com/p/practicalllms"
    },
    {
      title: "AI Done Right: Practical Applications for IP Professionals",
      date: "July 2023",
      source: "American Bar Association",
      link: "https://www.americanbar.org/groups/intellectual_property_law/events_cle/other-entity-events/ai-done-right-using-practical-ai-in-ip-law-practice/", 
    },
    {
      title: "Identifying Useful Large Language Models",
      date: "July 2023",
      source: "Machine Learning for Everyone",
      link: "https://www.youtube.com/live/_jCBqJYQ9zc?feature=share", 
    },
    {
      title: "Practical Perspective on LLMs",
      date:  "Jun 2023",
      source: "Arize AI",
      link: "https://youtu.be/dKBD-3hnjW0",
    },
    {
      title: "Lets Talk AI",
      date:  "May 2023",
      source: "Baptist Health",
      link: "https://baptisthealth.zoom.us/rec/share/gmKZf097DjLnmv98Bg4jTv9WuOyl2yv6CKPiHr7TPy03HFqlr7i2Pa2kWf10el6N.meU20VcGa5JxjPWu?startTime=1685030429000",
    },
    {
      title: "Generative AI tools change the nature of work",
      date:  "May 2023",
      source: "AI4Diversity",
      link: "https://youtu.be/wnKTld4CtR0",
    },
    {
      title: "The Peaks and Pits of Open-Source with Hugging Face",
      date:  "May 2023",
      source: "Analytics India",
      link: "https://analyticsindiamag.com/the-peaks-and-pits-of-open-source-with-hugging-face/",
    },
    {
      title: "Capabilities of LLMs",
      date: "Apr 2023",
      source: "Practical AI Podcast",
      link: "https://changelog.com/practicalai/219", 
    },
    {
      title: "Challenges and Opportunities for Keeping AI Open",
      date: "Apr 2023",
      source: "World Summit AI",
      link: "https://www.youtube.com/watch?v=aR3MvGy1PzM", 
    },
    {
      title: "ChatGPT and the coming Generative AI Revolution",
      date: "Jan 2023",
      source: "DataHour by Analytics Vidhya",
      link: "https://youtu.be/7zhgYrOQBeE", 
    },
    {
      title: "Introduction to programmatic labeling",
      date: "Aug 2022",
      source: "Snorkel AI",
      link: "https://youtu.be/tvuu5OGyMfE", 
    },
    {
      title: "The Mechanics of Data-First AI",
      date: "May 2022",
      source: "EmTech Digital",
      link: "https://event.technologyreview.com/emtech-digital-2022/speaker/392332/rajiv-shah", 
    },
    {
      title: "Rules: A Simple & Effective Machine Learning Approach",
      date: "Nov 2021",
      source: "St. Louis Data Science Meetup",
      link: "https://youtu.be/_Q3q4-UYZkA", 
    },
    {
      title: "Overcoming Issues with Small Data Sets when Building Machine Learning Models",
      date: "Dec 2020",
      source: "DataRobot",
      link: "https://www.youtube.com/watch?v=Ly3ogCE-GuI&t=1591s&ab_channel=DataRobot", 
    },
    {
      title: "Model Explainability with SHAP in DataRobot",
      date: "Dec 2020",
      source: "DataRobot",
      link: "https://www.youtube.com/watch?v=O4ZtUcZksQE&t=13s&ab_channel=DataRobot", 
    },
    {
      title: "When data leakage turns into a flood of trouble",
      date: "Oct 2020",
      source: "Practical AI Podcast",
      link: "https://changelog.com/practicalai/109", 
    },
    {
      title: "Model Interpretability",
      date: "Oct 2020",
      source: "AI Skunkworks Northeastern",
      link: "https://youtu.be/Oh6R47pGTfc", 
    },
    {
      title: "COVID-19: Data Science & Expertise",
      date: "Jun 2020",
      source: "GOTO Conference",
      link: "https://youtu.be/YVv01-f8TZE", 
    },
    {
      title: "Reproducing Deep Learning Models",
      date: "Oct 2019",
      source: "Data Skeptic",
      link: "https://dataskeptic.com/blog/episodes/2019/reproducing-deep-learning-models", 
    },
    {
      title: "Using Interpretability Tools To Improve Your Model",
      date: "Sep 2019",
      source: "Nashville Data Science",
      link: "https://www.youtube.com/live/syU6ubX9kVM?feature=share", 
    }
  ]
};

export default userData;

